# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.16.3

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - yarn install
    - step:
        name: Deploy to staging
        deployment: staging
        script:
          - eval `ssh-agent`
          - ssh-add /opt/atlassian/pipelines/agent/data/id_rsa
          - cat ./deploy_project_staging.sh | ssh -oStrictHostKeyChecking=no -v $USER@$HOST
          - echo "Deploying to staging environment"
    - step:
        name: Deploy to production
        deployment: production
        trigger: manual
        script:
          - eval `ssh-agent`
          - ssh-add /opt/atlassian/pipelines/agent/data/id_rsa
          - cat ./deploy_project.sh | ssh -oStrictHostKeyChecking=no -v $USER@$HOST
          - echo "Deploying to production environment"
